export const TIMEZONE = "Canada/Eastern";

export const DAYS_OF_WEEK = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"];

export const OPENING_HOURS = [
  {
    day: "Monday",
    hours: [
      "00:15",
      "00:30",
      "00:45",
      "01:00",
      "01:15",
      "01:30",
      "01:45",
      "02:00",
      "02:15",
      "02:30",
      "02:45",
      "03:00",
      "03:15",
      "03:30",
      "03:45",
      "04:00",
      "04:15",
      "04:30",
      "04:45",
      "05:00",
      "05:15",
      "05:30",
      "05:45",
      "06:00",
      "06:15",
      "06:30",
      "06:45",
      "07:00",
      "07:15",
      "07:30",
      "07:45",
      "08:00",
      "08:15",
      "08:30",
      "08:45",
      "09:00",
      "09:15",
      "09:30",
      "09:45",
      "10:00",
      "10:15",
      "10:30",
      "10:45",
      "11:00",
      "11:15",
      "11:30",
      "11:45",
      "12:00",
      "12:15",
      "12:30",
      "12:45",
      "13:00",
      "13:15",
      "13:30",
      "13:45",
      "14:00",
      "14:15",
      "14:30",
      "14:45",
      "15:00",
      "15:15",
      "15:30",
      "15:45",
      "16:00",
      "16:15",
      "16:30",
      "16:45",
      "17:00",
      "17:15",
      "17:30",
      "17:45",
      "18:00",
      "18:15",
      "18:30",
      "18:45",
      "19:00",
      "19:15",
      "19:30",
      "19:45",
      "20:00",
      "20:15",
      "20:30",
      "20:45",
      "21:00",
      "21:15",
      "21:30",
      "21:45",
      "22:00",
      "22:15",
      "22:30",
      "22:45",
      "23:00",
      "23:15",
      "23:30",
      "23:45",
    ],
  },
  {
    day: "Tuesday",
    hours: [
      "9:00",
      "9:30",
      "10:00",
      "10:30",
      "11:00",
      "13:00",
      "13:30",
      "14:00",
      "14:30",
      "15:00",
      "15:30",
      "16:00",
    ],
  },
  {
    day: "Wednesday",
    hours: [
      "9:00",
      "9:30",
      "10:00",
      "10:30",
      "11:00",
      "13:00",
      "13:30",
      "14:00",
      "14:30",
      "15:00",
      "15:30",
      "16:00",
    ],
  },
  {
    day: "Thursday",
    hours: [
      "9:00",
      "9:30",
      "10:00",
      "10:30",
      "11:00",
      "13:00",
      "13:30",
      "14:00",
      "14:30",
      "15:00",
      "15:30",
      "16:00",
      "22:00",
    ],
  },
  { day: "Friday", hours: [] },
  { day: "Saturday", hours: [] },
  { day: "Sunday", hours: [] },
];

export const TIMEZONE_OPTIONS = {
  Asia: [
    { value: "Asia/Tashkent", label: "Tashkent" },
    { value: "Asia/Tbilisi", label: "Tbilisi" },
    { value: "Asia/Tehran", label: "Tehran" },
    { value: "Asia/Thimphu", label: "Thimphu" },
    { value: "Asia/Tokyo", label: "Tokyo" },
    { value: "Asia/Tomsk", label: "Tomsk" },
    { value: "Asia/Ulaanbaatar", label: "Ulaanbaatar" },
    { value: "Asia/Urumqi", label: "Urumqi" },
    { value: "Asia/Ust-Nera", label: "Ust-Nera" },
    { value: "Asia/Vientiane", label: "Vientiane" },
    { value: "Asia/Vladivostok", label: "Vladivostok" },
    { value: "Asia/Yakutsk", label: "Yakutsk" },
    { value: "Asia/Yangon", label: "Yangon" },
    { value: "Asia/Yekaterinburg", label: "Yekaterinburg" },
    { value: "Asia/Yerevan", label: "Yerevan" },
  ],
  Atlantic: [
    { value: "Atlantic/Azores", label: "Azores" },
    { value: "Atlantic/Bermuda", label: "Bermuda" },
    { value: "Atlantic/Canary", label: "Canary" },
    { value: "Atlantic/Cape_Verde", label: "Cape Verde" },
    { value: "Atlantic/Faroe", label: "Faroe" },
    { value: "Atlantic/Madeira", label: "Madeira" },
    { value: "Atlantic/Reykjavik", label: "Reykjavik" },
    { value: "Atlantic/South_Georgia", label: "South Georgia" },
    { value: "Atlantic/Stanley", label: "Stanley" },
    { value: "Atlantic/St_Helena", label: "St Helena" },
  ],
  Australia: [
    { value: "Australia/Adelaide", label: "Adelaide" },
    { value: "Australia/Brisbane", label: "Brisbane" },
    { value: "Australia/Broken_Hill", label: "Broken Hill" },
    { value: "Australia/Darwin", label: "Darwin" },
    { value: "Australia/Eucla", label: "Eucla" },
    { value: "Australia/Hobart", label: "Hobart" },
    { value: "Australia/Lindeman", label: "Lindeman" },
    { value: "Australia/Lord_Howe", label: "Lord Howe" },
    { value: "Australia/Melbourne", label: "Melbourne" },
    { value: "Australia/Perth", label: "Perth" },
    { value: "Australia/Sydney", label: "Sydney" },
  ],
  Europe: [
    { value: "Europe/Amsterdam", label: "Amsterdam" },
    { value: "Europe/Andorra", label: "Andorra" },
    { value: "Europe/Astrakhan", label: "Astrakhan" },
    { value: "Europe/Athens", label: "Athens" },
    { value: "Europe/Belgrade", label: "Belgrade" },
    { value: "Europe/Berlin", label: "Berlin" },
    { value: "Europe/Bratislava", label: "Bratislava" },
    { value: "Europe/Brussels", label: "Brussels" },
    { value: "Europe/Bucharest", label: "Bucharest" },
    { value: "Europe/Budapest", label: "Budapest" },
    { value: "Europe/Busingen", label: "Busingen" },
    { value: "Europe/Chisinau", label: "Chisinau" },
    { value: "Europe/Copenhagen", label: "Copenhagen" },
    { value: "Europe/Dublin", label: "Dublin" },
    { value: "Europe/Gibraltar", label: "Gibraltar" },
    { value: "Europe/Guernsey", label: "Guernsey" },
    { value: "Europe/Helsinki", label: "Helsinki" },
    { value: "Europe/Isle_of_Man", label: "Isle of Man" },
    { value: "Europe/Istanbul", label: "Istanbul" },
    { value: "Europe/Jersey", label: "Jersey" },
    { value: "Europe/Kaliningrad", label: "Kaliningrad" },
    { value: "Europe/Kirov", label: "Kirov" },
    { value: "Europe/Kyiv", label: "Kyiv" },
    { value: "Europe/Lisbon", label: "Lisbon" },
    { value: "Europe/Ljubljana", label: "Ljubljana" },
    { value: "Europe/London", label: "London" },
    { value: "Europe/Luxembourg", label: "Luxembourg" },
    { value: "Europe/Madrid", label: "Madrid" },
    { value: "Europe/Malta", label: "Malta" },
    { value: "Europe/Mariehamn", label: "Mariehamn" },
    { value: "Europe/Minsk", label: "Minsk" },
    { value: "Europe/Monaco", label: "Monaco" },
    { value: "Europe/Moscow", label: "Moscow" },
    { value: "Europe/Oslo", label: "Oslo" },
    { value: "Europe/Paris", label: "Paris" },
    { value: "Europe/Podgorica", label: "Podgorica" },
    { value: "Europe/Prague", label: "Prague" },
    { value: "Europe/Riga", label: "Riga" },
    { value: "Europe/Rome", label: "Rome" },
    { value: "Europe/Samara", label: "Samara" },
    { value: "Europe/San_Marino", label: "San Marino" },
    { value: "Europe/Sarajevo", label: "Sarajevo" },
    { value: "Europe/Saratov", label: "Saratov" },
    { value: "Europe/Simferopol", label: "Simferopol" },
    { value: "Europe/Skopje", label: "Skopje" },
    { value: "Europe/Sofia", label: "Sofia" },
    { value: "Europe/Stockholm", label: "Stockholm" },
    { value: "Europe/Tallinn", label: "Tallinn" },
    { value: "Europe/Tirane", label: "Tirane" },
    { value: "Europe/Ulyanovsk", label: "Ulyanovsk" },
    { value: "Europe/Vaduz", label: "Vaduz" },
    { value: "Europe/Vatican", label: "Vatican" },
    { value: "Europe/Vienna", label: "Vienna" },
    { value: "Europe/Vilnius", label: "Vilnius" },
    { value: "Europe/Volgograd", label: "Volgograd" },
    { value: "Europe/Warsaw", label: "Warsaw" },
    { value: "Europe/Zagreb", label: "Zagreb" },
    { value: "Europe/Zurich", label: "Zurich" },
  ],
  Indian: [
    { value: "Indian/Antananarivo", label: "Antananarivo" },
    { value: "Indian/Chagos", label: "Chagos" },
    { value: "Indian/Christmas", label: "Christmas" },
    { value: "Indian/Cocos", label: "Cocos" },
    { value: "Indian/Comoro", label: "Comoro" },
    { value: "Indian/Kerguelen", label: "Kerguelen" },
    { value: "Indian/Mahe", label: "Mahe" },
    { value: "Indian/Maldives", label: "Maldives" },
    { value: "Indian/Mauritius", label: "Mauritius" },
    { value: "Indian/Mayotte", label: "Mayotte" },
    { value: "Indian/Reunion", label: "Reunion" },
  ],
  Pacific: [
    { value: "Pacific/Apia", label: "Apia" },
    { value: "Pacific/Auckland", label: "Auckland" },
    { value: "Pacific/Bougainville", label: "Bougainville" },
    { value: "Pacific/Chatham", label: "Chatham" },
    { value: "Pacific/Chuuk", label: "Chuuk" },
    { value: "Pacific/Easter", label: "Easter" },
    { value: "Pacific/Efate", label: "Efate" },
    { value: "Pacific/Fakaofo", label: "Fakaofo" },
    { value: "Pacific/Fiji", label: "Fiji" },
    { value: "Pacific/Funafuti", label: "Funafuti" },
    { value: "Pacific/Galapagos", label: "Galapagos" },
    { value: "Pacific/Gambier", label: "Gambier" },
    { value: "Pacific/Guadalcanal", label: "Guadalcanal" },
    { value: "Pacific/Guam", label: "Guam" },
    { value: "Pacific/Honolulu", label: "Honolulu" },
    { value: "Pacific/Kanton", label: "Kanton" },
    { value: "Pacific/Kiritimati", label: "Kiritimati" },
    { value: "Pacific/Kosrae", label: "Kosrae" },
    { value: "Pacific/Kwajalein", label: "Kwajalein" },
    { value: "Pacific/Majuro", label: "Majuro" },
    { value: "Pacific/Marquesas", label: "Marquesas" },
    { value: "Pacific/Midway", label: "Midway" },
    { value: "Pacific/Nauru", label: "Nauru" },
    { value: "Pacific/Niue", label: "Niue" },
    { value: "Pacific/Norfolk", label: "Norfolk" },
    { value: "Pacific/Noumea", label: "Noumea" },
    { value: "Pacific/Pago_Pago", label: "Pago Pago" },
    { value: "Pacific/Palau", label: "Palau" },
    { value: "Pacific/Pitcairn", label: "Pitcairn" },
    { value: "Pacific/Pohnpei", label: "Pohnpei" },
    { value: "Pacific/Port_Moresby", label: "Port Moresby" },
    { value: "Pacific/Rarotonga", label: "Rarotonga" },
    { value: "Pacific/Saipan", label: "Saipan" },
    { value: "Pacific/Tahiti", label: "Tahiti" },
    { value: "Pacific/Tarawa", label: "Tarawa" },
    { value: "Pacific/Tongatapu", label: "Tongatapu" },
    { value: "Pacific/Wake", label: "Wake" },
    { value: "Pacific/Wallis", label: "Wallis" },
  ],
  UTC: [{ value: "UTC", label: "UTC" }],
  "Manual Offsets": [
    { value: "UTC-12", label: "UTC-12" },
    { value: "UTC-11.5", label: "UTC-11:30" },
    { value: "UTC-11", label: "UTC-11" },
    { value: "UTC-10.5", label: "UTC-10:30" },
    { value: "UTC-10", label: "UTC-10" },
    { value: "UTC-9.5", label: "UTC-9:30" },
    { value: "UTC-9", label: "UTC-9" },
    { value: "UTC-8.5", label: "UTC-8:30" },
    { value: "UTC-8", label: "UTC-8" },
    { value: "UTC-7.5", label: "UTC-7:30" },
    { value: "UTC-7", label: "UTC-7" },
    { value: "UTC-6.5", label: "UTC-6:30" },
    { value: "UTC-6", label: "UTC-6" },
    { value: "UTC-5.5", label: "UTC-5:30" },
    { value: "UTC-5", label: "UTC-5" },
    { value: "UTC-4.5", label: "UTC-4:30" },
    { value: "UTC-4", label: "UTC-4" },
    { value: "UTC-3.5", label: "UTC-3:30" },
    { value: "UTC-3", label: "UTC-3" },
    { value: "UTC-2.5", label: "UTC-2:30" },
    { value: "UTC-2", label: "UTC-2" },
    { value: "UTC-1.5", label: "UTC-1:30" },
    { value: "UTC-1", label: "UTC-1" },
    { value: "UTC-0.5", label: "UTC-0:30" },
    { value: "UTC+0", label: "UTC+0" },
    { value: "UTC+0.5", label: "UTC+0:30" },
    { value: "UTC+1", label: "UTC+1" },
    { value: "UTC+1.5", label: "UTC+1:30" },
    { value: "UTC+2", label: "UTC+2" },
    { value: "UTC+2.5", label: "UTC+2:30" },
    { value: "UTC+3", label: "UTC+3" },
    { value: "UTC+3.5", label: "UTC+3:30" },
    { value: "UTC+4", label: "UTC+4" },
    { value: "UTC+4.5", label: "UTC+4:30" },
    { value: "UTC+5", label: "UTC+5" },
    { value: "UTC+5.5", label: "UTC+5:30" },
    { value: "UTC+5.75", label: "UTC+5:45" },
    { value: "UTC+6", label: "UTC+6" },
    { value: "UTC+6.5", label: "UTC+6:30" },
    { value: "UTC+7", label: "UTC+7" },
    { value: "UTC+7.5", label: "UTC+7:30" },
    { value: "UTC+8", label: "UTC+8" },
    { value: "UTC+8.5", label: "UTC+8:30" },
    { value: "UTC+8.75", label: "UTC+8:45" },
    { value: "UTC+9", label: "UTC+9" },
    { value: "UTC+9.5", label: "UTC+9:30" },
    { value: "UTC+10", label: "UTC+10" },
    { value: "UTC+10.5", label: "UTC+10:30" },
    { value: "UTC+11", label: "UTC+11" },
    { value: "UTC+11.5", label: "UTC+11:30" },
    { value: "UTC+12", label: "UTC+12" },
    { value: "UTC+12.75", label: "UTC+12:45" },
    { value: "UTC+13", label: "UTC+13" },
    { value: "UTC+13.75", label: "UTC+13:45" },
    { value: "UTC+14", label: "UTC+14" },
  ],
};
